# Generated by Django 4.2.23 on 2025-07-30 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sensor",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="sensor",
            name="description",
        ),
        migrations.RemoveField(
            model_name="sensor",
            name="name",
        ),
        migrations.RemoveField(
            model_name="sensor",
            name="rpm",
        ),
        migrations.RemoveField(
            model_name="sensor",
            name="temperature",
        ),
        migrations.RemoveField(
            model_name="sensor",
            name="user",
        ),
        migrations.RemoveField(
            model_name="sensor",
            name="vibration",
        ),
        migrations.AddField(
            model_name="sensor",
            name="kind",
            field=models.CharField(
                choices=[
                    ("temperature", "temperature"),
                    ("vibration", "vibration"),
                    ("current", "current"),
                ],
                default="temperature",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="sensor",
            name="threshold",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sensor",
            name="unit",
            field=models.CharField(default="°C", max_length=20),
        ),
        migrations.CreateModel(
            name="Workspace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ts", models.DateTimeField(auto_now_add=True)),
                ("value", models.FloatField()),
                (
                    "sensor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.sensor"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Machine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("kind", models.CharField(default="motor", max_length=50)),
                ("x", models.IntegerField(default=100)),
                ("y", models.IntegerField(default=100)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="machines",
                        to="core.workspace",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ts", models.DateTimeField(auto_now_add=True)),
                ("level", models.CharField(default="WARN", max_length=10)),
                ("message", models.CharField(max_length=200)),
                (
                    "sensor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.sensor",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="core.workspace",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="sensor",
            name="machine",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sensors",
                to="core.machine",
            ),
        ),
    ]
