name: Checks
on: [push]

jobs:
  test-lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Create backend .env for CI
        env:
          DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
        run: |
          cat > backend/.env <<EOF
          DEBUG=1
          DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY:-dev-secret}
          DB_HOST=db
          DB_PORT=5432
          DB_NAME=dev_db
          DB_USER=devuser
          DB_PASSWORD=changeme
          REDIS_HOST=redis
          REDIS_PORT=6379
          ALLOWED_HOSTS=*
          EOF

      - name: Start infra (DB + Redis)
        run: docker compose up -d db redis

      - name: Wait for database
        run: docker compose run --rm backend sh -lc "/py/bin/python app/manage.py wait_for_db"

      - name: Test
        run: docker compose run --rm backend sh -lc "/py/bin/python app/manage.py test -v 2"

      - name: Lint
        run: docker compose run --rm backend sh -lc "/py/bin/flake8"

      - name: Teardown
        if: always()
        run: docker compose down -v
