---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: Ubuntu-24.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Wait for database
        run: cd backend && docker compose run --rm app python manage.py wait_for_db
      - name: Test
        run: cd backend && docker compose run --rm app python manage.py test
      - name: Lint
        run: cd backend && docker compose run --rm app flake8