name: Checks
on: [push]

jobs:
  test-lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Debug services
        run: docker compose -f docker-compose.yml config --services

      - name: Start infra (DB + Redis)
        run: docker compose up -d db redis

      - name: Wait for database
        run: docker compose run --rm backend sh -lc "python app/manage.py wait_for_db"

      - name: Test
        run: docker compose run --rm backend sh -lc "python app/manage.py test -v 2"

      - name: Lint
        run: docker compose run --rm backend sh -lc "flake8"

      - name: Teardown
        if: always()
        run: docker compose down -v
